# Generated by Django 5.0 on 2023-12-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SantaAssign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santas',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
